# CDS definition with one prefetch template
[[cds_services]]
hook = "patient-view"
title = "Static CDS Service Example"
description = "An example of a CDS Service that returns a static set of cards"
id = "static-patient-greeter"
[cds_services.prefetch]
patientToGreet = "Patient/{{context.patientId}}"

# Order select
[[cds_services]]
id = "radiology"
hook = "order-select"
title = "Radiology order select"
description = "This hook can be used when intiating radiology related actions"

# Order select
[[cds_services]]
id = "radiology-order"
hook = "order-sign"
title = "Radiology order sign"
description = "This hook can be used when sigining radiology related orders"


# CDS definition with an empty prefetch
[[cds_services]]
id = "book-imaging-center"
hook = "order-dispatch"
title = "Book an imaging center"
description = "This hook can be used when booking imaging center"

# Order select
[[cds_services]]
id = "regular-medications"
hook = "order-sign"
title = "Prescribe regular medications"
description = "This hook can be used when sigining regular medication other than vaccines"

# Order select
[[cds_services]]
id = "vaccines"
hook = "order-sign"
title = "Prescribe vaccines"
description = "This hook can be used when sigining vaccines"
